import "@/styles/globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return <>
  <Head>
        <title>Scent Works</title>
        <link rel="icon" href="/logo1.jpg" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />  
      </Head> 
  <Navbar/>
  <Component {...pageProps} />
  {/* <Footer/> */}
  </>
}
